version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        image: laravel_app
        container_name: pkpa_api
        restart: unless-stopped
        tty: true
        volumes:
            - .:/var/www/html
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: pkpa_api_nginx
        restart: unless-stopped
        ports:
            - "9090:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html # Merujuk ke root proyek Laravel
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
